### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [ayoza/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - please make sure all URLs are embedded/formatted correctly
- [x] All relevant code examples written with backticks (```)
  - please make sure all commands/code is formatted correctly
- [x] All screenshots correspond to the described steps
  - please update the last image to run the method you came up with
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃 
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by ayoza** [comment]
Hello! I was wondering where I need backticks. Also, I got a comment from the Professor that said my method to save time while remotely running was effective so I was wondering what I needed to improve there.

**Comment by farnaf** [comment]
Hi there! 
- You can use backticks for all terminal commands, similar to [part 4 in lab 1](https://ucsd-cse15l-w22.github.io/week/week1/#part-4--run-some-commands) - e.g., `cd`, `ls`, ..., `$ ssh-keygen`, etc.
- Oh sorry! Your method `$ ssh cs15lwi22zz@ieng6.ucsd.edu “javac [file].java; java [class]”` is great. Only the screenshot doesn't correspond (login and running are separate steps in the image). Updating the rubric

**Comment by ayoza** [comment]
Thank you. It should all be fixed now. I am unsure how to request a regrade since I don't think my submission has been graded yet.

**Comment by farnaf** [comment]
Sweet! The grades aren't released yet, but I'll update your score to 1/1 - no need for a regrade request (:
